//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int Id { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime Date { get; set; }
        public double Duration { get; set; }
        public string Comment { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
